/**
 * Vitest globalSetup — runs once BEFORE any test environment is created.
 * Saves the real Node.js native fetch (undici-backed) to a temp file so
 * per-environment setupFiles can restore it after happy-dom clobbers it.
 *
 * globalSetup runs in the main vitest process (not worker threads),
 * so createRequire is always available here.
 */
import { createRequire } from "node:module"
import { writeFileSync } from "node:fs"
import { join } from "node:path"

const _require = createRequire(import.meta.url)
const undici = _require("undici") as typeof import("undici")

// Write a tiny CJS module that re-exports the native fetch function.
// This file lives in node_modules/.vitest and is imported by setup.ts
// using a direct path — no bundler transforms, no ESM complications.
const dir = join(process.cwd(), "node_modules", ".vitest")
const code = `// Auto-generated by globalSetup — do not edit
module.exports = ${JSON.stringify(undici.fetch.toString())};
`
writeFileSync(join(dir, "native-fetch.cjs"), code, "utf-8")

// Also store as a simple global for threads workers
process.env.__VITEST_NATIVE_FETCH__ = undici.fetch.toString()

export default function setup() {
  // Nothing to do here — the side effects above are sufficient
}
